name: Deploy Example
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print a secret (for demo)
        run: 'echo "Deploying with key: ${{secrets:VERCEL_TOKEN}}"'
        env:
          VERCEL_TOKEN: "${{secrets: VERCEL_TOKEN}}"
